# Increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=false

# NeoForge / Minecraft
minecraft_version=26.1.2
neoforge_version=26.1.2.76

# Mod Properties
mod_version=0.0.9-alpha
maven_group=com.lycanitesmobs
archives_base_name=lycanitesmobs
